In [6]:
import pandas as pd
import numpy as np
from pathlib import Path

In [11]:
# Load merged AQI dataset
df = pd.read_csv("../data/processed/merged_aqi.csv")

# Display first 5 rows
df.head()

,Date,PM2.5,PM10,Ozone,SO2,NO2,Station,Source_File
0,2024-01-01,62.57,128.77,35.72,0.98,26.37,Bandra Kurla Complex,BKC 24-26
1,2024-01-02,75.46,106.93,24.85,1.15,18.78,Bandra Kurla Complex,BKC 24-26
2,2024-01-03,61.45,106.22,29.49,1.84,33.91,Bandra Kurla Complex,BKC 24-26
3,2024-01-04,44.12,110.50,53.18,0.94,20.06,Bandra Kurla Complex,BKC 24-26
4,2024-01-05,85.60,133.02,29.12,1.04,34.30,Bandra Kurla Complex,BKC 24-26

In [12]:
print("=" * 60)
print("Dataset Shape")
print("=" * 60)

print(df.shape)

print("\n")

print("=" * 60)
print("Dataset Information")
print("=" * 60)

df.info()

============================================================
Dataset Shape
============================================================
(31716, 8)


============================================================
Dataset Information
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31716 entries, 0 to 31715
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         31716 non-null  object
 1   PM2.5        25557 non-null  float64
 2   PM10         25803 non-null  float64
 3   Ozone        24830 non-null  float64
 4   SO2          25089 non-null  float64
 5   NO2          26087 non-null  float64
 6   Station      31716 non-null  object
 7   Source_File  31716 non-null  object
dtypes: float64(5), object(3)
memory usage: 1.9+ MB

In [13]:
print("=" * 60)
print("Missing Values")
print("=" * 60)

missing = df.isnull().sum()

print(missing)

print("\nPercentage Missing")

print((missing / len(df) * 100).round(2))

============================================================
Missing Values
============================================================
Date              0
PM2.5          6159
PM10           5913
Ozone          6886
SO2            6627
NO2            5629
Station           0
Source_File       0
dtype: int64

Percentage Missing
Date            0.00
PM2.5          19.42
PM10           18.64
Ozone          21.71
SO2            20.89
NO2            17.75
Station         0.00
Source_File     0.00
dtype: float64

In [15]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows: {duplicates}")

df.drop_duplicates(inplace=True)

print("Dataset Shape After Removing Duplicates:")
print(df.shape)

Duplicate Rows: 0
Dataset Shape After Removing Duplicates:
(31716, 8)

In [16]:
df["Date"] = pd.to_datetime(df["Date"])

print(df["Date"].dtype)

datetime64[ns]

In [17]:
pollutants = [
    "PM2.5",
    "PM10",
    "Ozone",
    "SO2",
    "NO2"
]

for col in pollutants:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[pollutants].dtypes)

PM2.5    float64
PM10     float64
Ozone    float64
SO2      float64
NO2      float64
dtype: object

In [18]:
print(df[pollutants].isnull().sum())

PM2.5    6159
PM10     5913
Ozone    6886
SO2      6627
NO2      5629
dtype: int64

In [19]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["DayOfWeek"] = df["Date"].dt.day_name()

df.head()

,Date,PM2.5,PM10,Ozone,SO2,NO2,Station,Source_File,Year,Month,Day,DayOfWeek
0,2024-01-01,62.57,128.77,35.72,0.98,26.37,Bandra Kurla Complex,BKC 24-26,2024,1,1,Monday
1,2024-01-02,75.46,106.93,24.85,1.15,18.78,Bandra Kurla Complex,BKC 24-26,2024,1,2,Tuesday
2,2024-01-03,61.45,106.22,29.49,1.84,33.91,Bandra Kurla Complex,BKC 24-26,2024,1,3,Wednesday
3,2024-01-04,44.12,110.50,53.18,0.94,20.06,Bandra Kurla Complex,BKC 24-26,2024,1,4,Thursday
4,2024-01-05,85.60,133.02,29.12,1.04,34.30,Bandra Kurla Complex,BKC 24-26,2024,1,5,Friday

In [20]:
df.describe(include="all")

,Date,PM2.5,PM10,Ozone,SO2,NO2,Station,Source_File,Year,Month,Day,DayOfWeek
count,31716,25557.000000,25803.000000,24830.000000,25089.000000,26087.000000,31716,31716,31716.000000,31716.000000,31716.000000,31716
unique,NaN,NaN,NaN,NaN,NaN,NaN,36,36,NaN,NaN,NaN,7
top,NaN,NaN,NaN,NaN,NaN,NaN,Bandra Kurla Complex,BKC 24-26,NaN,NaN,NaN,Monday
freq,NaN,NaN,NaN,NaN,NaN,NaN,881,881,NaN,NaN,NaN,4536
mean,2025-03-16 00:00:00,34.006825,90.116112,25.258870,9.285044,26.537339,NaN,NaN,2024.754824,5.920545,15.701476,NaN
min,2024-01-01 00:00:00,0.010000,0.070000,0.010000,0.010000,0.010000,NaN,NaN,2024.000000,1.000000,1.000000,NaN
25%,2024-08-08 00:00:00,16.480000,50.065000,9.070000,3.160000,11.550000,NaN,NaN,2024.000000,3.000000,8.000000,NaN
50%,2025-03-16 00:00:00,28.770000,79.860000,17.750000,6.870000,19.710000,NaN,NaN,2025.000000,5.000000,16.000000,NaN
75%,2025-10-22 00:00:00,46.380000,118.235000,33.750000,12.710000,33.230000,NaN,NaN,2025.000000,9.000000,23.000000,NaN
max,2026-05-30 00:00:00,974.140000,1000.000000,404.950000,193.820000,325.390000,NaN,NaN,2026.000000,12.000000,31.000000,NaN
std,NaN,24.815802,55.284881,23.045785,9.671625,23.405505,NaN,NaN,0.724985,3.459310,8.785024,NaN

In [21]:
output_path = "../data/processed/cleaned_aqi.csv"

df.to_csv(output_path, index=False)

print(f"Cleaned dataset saved to:\n{output_path}")

Cleaned dataset saved to:
../data/processed/cleaned_aqi.csv